# Default settings
[build]
publish = "dist/"
command = "npm run build"

# Deployment from production branch commits
# [context.production]

# Preview builds for pull requests
# [context.deploy-preview]

# All other commits
[context.branch-deploy]
  command = "npm run lint"
